caracterizacion_S/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    #incluir archivo de la app
    path('', include('software_caracterizacion.urls')),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

software_caracterizacion/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #LOGIN
    path('inicio', views.inicio,name='inicio'),

    path('', views.userLogin, name='user-login'),
    path('logout/', views.logout_user, name='logout'),
    #PROCESOS
     path('procesos',views.procesos,name='procesos'),
     path('procesos/crear_proceso', views.crear_proceso,name='crear_proceso'),
     path('detalle_proceso/<int:id>', views.detalle_proceso,name='detalle_proceso'),
     path('editar_proceso/<int:id>',views.editar_proceso,name='editar_proceso'),
     path('eliminar_proceso/<int:id>',views.eliminar_proceso,name='eliminar_proceso'),

    #AUTOMATIZACION PROCESO
    path('automatizacion_proceso/<int:id>', views.automatizacion_proceso,name='automatizacion_proceso'),
    #  ####
     path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
     path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
     path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
     path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    path('lista/', views.ListaProcesosView.as_view(), name='lista'),
    path('listar-procesos/', views.ListProcesosPdf.as_view(), name='procesos_all'),
    # 
    
    path('ajax/load-responsable/', views.load_responsable, name='ajax_load_responsable'), # AJAX
]

software_caracterizacion/models.py
from cgitb import text
from django.db import models
from django.db import models
from .clientes import *
from django.contrib.auth.models import User
import datetime
# Create your models here.

class TipoUnidad(models.Model):
    nombre = models.CharField(max_length=150, null=True, unique=True, verbose_name='Tipo de unidad')

    def __str__(self):
        fila =  self.nombre
        return fila
   
class Usuario(models.Model):
    nombre = models.CharField(max_length=150, null=True, unique=True, verbose_name='Usuario que realiza la solicitud')

    def __str__(self):
        fila =  self.nombre
        return fila
    
class Plataforma(models.Model):
    nombre = models.CharField(max_length=150, null=True, unique=True, verbose_name='Plataforma a la cual va dirigida la solicitud:')

    def __str__(self):
        fila =  self.nombre
        return fila
     
class Unidades(models.Model):
    nombre = models.CharField(max_length=150, null=True, verbose_name='Nombre de la unidad')
    def __str__(self):
        fila = self.nombre
        return fila

class ResponsableUnidad(models.Model):
    nombre = models.CharField(max_length=100)
    unidades = models.ForeignKey(Unidades,null=True, blank=True, on_delete=models.PROTECT, verbose_name='Nombre de la unidad')
    def __str__(self):
        fila = self.nombre
        return fila



class Procesos(models.Model):
    # id = models.AutoField(primary_key=True)
    nom_pro = models.CharField(max_length=150, null=True, verbose_name='Nombre del proceso ', unique=True)
    tipoprocesoid = models.ForeignKey(TipoUnidad,null=True, blank=False, on_delete=models.PROTECT, verbose_name='Tipo de unidad que recibe la solicitud')
    plataformaid = models.ForeignKey(Plataforma,null=True, blank=True, on_delete=models.PROTECT, verbose_name='Plataforma a la cual va dirigida la solicitud:')
    usuarioid = models.ForeignKey(Usuario,null=True, blank=True, on_delete=models.PROTECT, verbose_name='Usuario que realiza la solicitud')
    pre_pro = models.CharField(max_length=150, verbose_name='Pregunta base del proceso')
    res_pro = models.CharField(max_length=150, verbose_name='Respuesta base del proceso')
    
    
    doc_pro = models.CharField(max_length=2, choices=suceptible_automatizar, default='No',verbose_name='¿EL proceso requiere documentos para su solución?')
    rep_pro = models.CharField(max_length=150, verbose_name='Persona responsable del proceso')
    tie_pro = models.CharField(max_length=100, verbose_name='Tiempo en resolver la solicitud del usuario')
    tie_sel = models.CharField(max_length=8, choices=horas_proceso, default='Horas', verbose_name='')

    user = models.ForeignKey(User, editable=False, verbose_name='Usuario', on_delete=models.CASCADE, null=True, related_name='Procesos')
    aut_pro = models.CharField(max_length=2, choices=suceptible_automatizar, default='No',verbose_name='Automatizar')

    day  = datetime.datetime.now()
    formatedDay  = day.strftime("%Y/%m/%d")
    formatedHora = day.strftime("%H:%M:%S")
    fec_pro = models.CharField(max_length=50, editable=False, default=formatedDay, verbose_name='Fecha')
    hor_pro = models.CharField(max_length=50, editable=False, default=formatedHora, verbose_name='Hora')

    unidadesid = models.ForeignKey(Unidades,null=True, blank=True, on_delete=models.PROTECT, verbose_name='Unidad que recibe la solicitud')
    responsableid = models.ForeignKey(ResponsableUnidad,null=True, blank=True, on_delete=models.PROTECT, verbose_name='Responsable de la unidad que recibe la solicitud')
    
 
    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.nom_pro, self.id)

software_caracterizacion/forms.py
from distutils.text_file import TextFile
from logging import PlaceHolder
from selectors import SelectSelector
#from tkinter import Widget
#from attr import attr
from django.forms import TextInput, TimeInput, ModelForm, RadioSelect, Textarea, Select

from .models import *

class ProcesosFormulario(ModelForm):
    class Meta:
        model = Procesos
        fields = '__all__'
        widgets = {
            #PREGUNTAR PORQUE NO FUNCIONA EL PLACEHOLDER
            
            'nom_pro':TextInput(attrs={'type': 'text','class' : 'nombre_proceso', 'placeholder':'Ej: Cambio de contraseña de TAU', 'pattern' : '[a-zA-ZñÑáéíóúÁÉÍÓÚ\s]+', 'required' : True }),

            'pre_pro':Textarea(attrs={'type': 'text','class' : 'pregunta_proceso', 'placeholder':'Ej: ¿Comó recuperar mi contraseña de TAU?', 'required' : 'required', 'rows': 3  }),
            
            'res_pro':Textarea(attrs={'type': 'text','class' : 'respuesta_proceso', 'placeholder':'Ej: Para soporte de la plataforma TAU, por favor escribir al siguiente correo tau-ayuda@unicesmag.edu.co, este proceso no corresponde a la Jefatura de Desarrollo de Software', 'required' : 'required', 'rows': 3}),

            'aut_pro':RadioSelect(attrs={'type': 'radio','class' : 'automatizacion_proceso',  }),

            'fec_pro':TimeInput(attrs={'type': 'month','class' : 'fech_creacion_proceso', 'placeholder':'Creacion del proceso', 'required' : 'required' }),

            'hor_pro':TimeInput(attrs={'type': 'time','class' : 'hor_creacion_proceso', 'placeholder':'Creacion Hora del proceso', 'required' : 'required'}),

            'tie_pro':TextInput(attrs={'type': 'number','class' : 'tiem_proceso', 'placeholder':'Ej: 1', 'pattern' : '[0-9]+', 'min':'1', 'max':'59','required' : 'required' }),
        
            'usuarioid':Select(attrs={'required' : 'required' }),
            'plataformaid':Select(attrs={'required' : 'required' }),
            
            'programaid':Select(attrs={'required' : 'required' }),
            'responsableid':Select(attrs={'required' : 'required' }),
            
            
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['responsableid'].queryset = ResponsableUnidad.objects.none()

        if 'unidadesid' in self.data:
            try:
                unidades_id = int(self.data.get('unidadesid'))
                self.fields['responsableid'].queryset = ResponsableUnidad.objects.filter(unidades_id=unidades_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk and self.instance.unidadesid:
            self.fields['responsableid'].queryset = self.instance.unidadesid.responsableunidad_set.order_by('nombre')


software_caracterizacion/views.py
from django.http import HttpResponse
from django.views.generic import ListView, View
from django.shortcuts import get_object_or_404, redirect, render
from .models import   *
from django.contrib import messages
from .forms import ProcesosFormulario
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from software_caracterizacion.utils import render_to_pdf
from django.core.paginator import Paginator
from django.http import Http404
import datetime
#PDF
class ListaProcesosView(ListView):
    model = Procesos
    template_name = "report/pdf.html"
    context_object_name = 'procesos'

class ListProcesosPdf(View):
    def get(self, request, *args, **kwargs):
        procesos = Procesos.objects.filter(user=request.user).order_by('-fec_pro')
        user = request.user
        day  = datetime.datetime.now()
        formatedDay  = day.strftime("%Y/%m/%d")
        data = {
            'procesos': procesos,
            'user': user,
            'date': formatedDay
        }
        
        pdf = render_to_pdf('report/lista.html', data)
        
        return HttpResponse(pdf, content_type='application/pdf')
#PDF
# Create your views here.
@login_required(login_url="user-login")
def inicio(request):
    return render(request, 'login/inicio.html')

#LOGIN
def index_Login(request):
    return render(request, 'login/index_Login.html')


def userLogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None:
            
            login(request, user)
            
            return redirect('inicio')
        else:
            messages.warning(request,'No te has identificado correctamente.')
    return render(request,'login/index_Login.html')

def logout_user(request):
    logout(request)
    return redirect('user-login')

#PROCESOS
@login_required(login_url="user-login")
def procesos(request):
    # BUSCADOR
    if 'q' in request.GET:
        q = request.GET['q']
        no_proceso = Procesos.objects.filter(user=request.user).count()
        busqueda = Procesos.objects.filter(nom_pro__icontains=q)
        contador = busqueda.count()
        #
        page = request.GET.get('page', 1)
        try:
            paginator = Paginator(busqueda, 5)
            busqueda = paginator.page(page)
        except :
            raise Http404
        #
        if contador == 0:
                messages.warning(request, 'No se encontró ningún registro')
                no_proceso = Procesos.objects.filter(user=request.user).count()
                busqueda = Procesos.objects.filter(user=request.user).order_by('-fec_pro').order_by('-hor_pro')
                page = request.GET.get('page', 1)
                try:
                    paginator = Paginator(busqueda, 5)
                    busqueda = paginator.page(page)
                except :
                    raise Http404
                return render(request, 'procesos/index.html', {'no_proceso': no_proceso, 'entity': busqueda, 'paginator':paginator})
    else:
        no_proceso = Procesos.objects.filter(user=request.user).count()
        busqueda = Procesos.objects.filter(user=request.user).order_by('-fec_pro').order_by('-hor_pro')
        page = request.GET.get('page', 1)
        try:
            paginator = Paginator(busqueda, 5)
            busqueda = paginator.page(page)
        except :
            raise Http404
    return render(request, 'procesos/index.html', {'no_proceso': no_proceso, 'entity': busqueda, 'paginator':paginator})
@login_required(login_url="user-login")
def crear_proceso(request):
    if request.method == 'POST':
        form_procesos = ProcesosFormulario(request.POST)
        if form_procesos.is_valid():
            post = form_procesos.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'Proceso creado correctamente')
            return redirect('crear_proceso')
        else:
            messages.success(request, 'Este proceso ya existe')
    else:
        # crear nuevoi objeto
        form_procesos = ProcesosFormulario()
    return render(request, 'procesos/crear.html', {'form_procesos': form_procesos})

@login_required(login_url="user-login")
def load_responsable(request):
    unidades_id = request.GET.get('unidades_id')
    responsableunidad = ResponsableUnidad.objects.filter(unidades_id=unidades_id).all()
    return render(request, 'procesos/city_dropdown_list_options.html', {'responsableunidad': responsableunidad})

@login_required(login_url="user-login")
def detalle_proceso(request, id):
    #proceso = Procesos.objects.get(pk=ide_pro)
    proceso = get_object_or_404(Procesos, pk=id)
    return render(request,'procesos/detallemodal.html', {'proceso': proceso})

    
@login_required(login_url="user-login")
def editar_proceso(request, id):
    proceso = get_object_or_404(Procesos, pk=id)
    get_tipo = proceso.user.id #usuario del procesoz
    if request.user.id == get_tipo:
        if request.method == 'POST':
        
            form_procesos = ProcesosFormulario(request.POST, instance=proceso)
            if form_procesos.is_valid():
                form_procesos.save()
                messages.success(request, 'Proceso editado correctamente')
                return redirect('procesos')
        else:
            # crear nuevoi objeto
            form_procesos = ProcesosFormulario(instance=proceso)
        return render(request, 'procesos/editar.html', {'form_procesos': form_procesos})
    else:
        messages.success(request, 'Esta acción no es permitida')
        return render(request, 'login/inicio.html')


@login_required(login_url="user-login")
def eliminar_proceso(request, id):
    proceso = Procesos.objects.get(id=id)
    proceso.delete()
    messages.success(request, 'Proceso eliminado correctamente')
    return redirect('procesos')

# automatizacion proceso
@login_required(login_url="user-login")
def automatizacion_proceso(request, id):
    proceso = get_object_or_404(Procesos, pk=id)
    get_tipo = proceso.tipoprocesoid
    
    
    if request.method == 'POST':
        form_procesos = ProcesosFormulario(request.POST, instance=proceso)
        if form_procesos.is_valid():
            form_procesos.save()
            messages.success(request, 'Proceso ejecutado correctamente')
            return redirect('procesos')
    else:
        # crear nuevoi objeto
        form_procesos = ProcesosFormulario(instance=proceso)
    return render(request, 'procesos/automatizar/detalles_Automatizar.html', {'form_procesos': form_procesos, 'proceso': proceso, 'get_tipo':get_tipo})
    

software_caracterizacion/templates/procesos/city_dropdown_list_options.html
<option value="">---------</option>
{% for responsable in responsableunidad %}
<option value="{{ responsable.pk }}">{{ responsable.nombre }}</option>
{% endfor %}

software_caracterizacion/templates/procesos/crear.html
{% extends "base.html" %}
{% block titulo %} Agregar nuevo proceso {% endblock %}

{% load static %}

{% block contenido %} 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/oculatr_radio.css' %}" />
  
</head>
<body>
  
  <div class="card borcrear">
    <div class="card-header bg-info borcrear">
      
      <div class="container text-center">
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <i>Agregar un proceso</i> <br>
            <a type="button" class="btn btn-primary btn-sm" href="{% url 'procesos' %}">Regresar</a>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <h4 class="card-title" id="datos_titulo">Datos del proceso</h4>
        {% include 'procesos/form.html' %}
    </div>
  </div>

</body>
</html>

{% endblock %}
    

software_caracterizacion/templates/procesos/detallemodal.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">Detalle del proceso</h2>
      <button class="btn btn-danger" type="button" data-dismiss="modal">
        X
      </button>
    </div>

    <style>
      #nota{
        font-size: .8em;
    color: #859099;
    font-style: italic;
    text-align: right;
      }
    </style>
    <form action="" method="POST" class="formdet">
      <div class="modal-body">
        <div class="container">
          <div class="mb-3">
            <div class="row">
              <div class="col-sm-8 fecha_hor">
                Fecha de creación: {{proceso.fec_pro}}
              </div>
              <div class="col-sm-4 fecha_hor">
                Hora de creación: {{proceso.hor_pro}}
              </div>
              <span id="nota">Nota: Usted va 5 horas por detrás de la hora normal.</span>
            </div>
          </div>
          <br />
          <!-- tabla -->
          <table class="table table-bordered border-primary">
            <tbody>
              
              <tr>
                <th>Responsable del proceso: {{proceso.rep_pro}}</th>
                <!-- <td>Nombre: {{proceso.nom_pro}}</td> -->
                <td><b>Usuario que realiza la petición: </b>{{proceso.usuarioid}}</td>
              </tr>
              
              <tr>
                <td><b>Tipo de unidad: </b>{{proceso.tipoprocesoid}}</td>
                <td><b>¿Necesidad de documentos? </b>{{proceso.doc_pro}}</td>
              </tr>

              <tr>
                <td><b>Pregunta: </b>{{proceso.pre_pro}}</td>
                <td><b>Respuesta: </b>{{proceso.res_pro}}</td>
              </tr>
            </tbody>
          </table>
          <!-- tablafin -->
        </div>
        
      </div>
    </form>
  </div>
</div>

software_caracterizacion/templates/procesos/editar.html
{% extends "base.html" %}
{% block titulo %}  {% endblock %}

{% load static %}

{% block contenido %} 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/oculatr_radio.css' %}" />
  <title>Document</title>
  
</head>
<body>

  <div class="card borcrear">
    <div class="card-header bg-info borcrear">
      <div class="container text-center">
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <i>Editar proceso</i> <br>
            <a type="button" class="btn btn-primary btn-sm" href="{% url 'procesos' %}">Regresar</a>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <h4 class="card-title" id="datos_titulo">Datos del proceso</h4>
        {% include 'procesos/form.html' %}
        
    </div>
  </div>

  
</body>

</html>

{% endblock %}
    

software_caracterizacion/templates/procesos/form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/formu.css' %}" />
    <script src="{% static 'js/index.js' %}"></script>
  </head>
  <body>
    <form enctype="multipart/form-data" method="post" id="personForm" data-responsable-url="{% url 'ajax_load_responsable' %}">
      {% csrf_token %}
      
      <div class="container">
        <div class="row mt-4 mt-4 mb-4">
          <div class="col-6">
            <span id="label_nom_pro">{{ form_procesos.nom_pro.label }}</span>
            {{ form_procesos.nom_pro }}
          </div>
          <div class="col-6">
            
            <span id="label_rep_pro">{{ form_procesos.rep_pro.label }}</span>
      {{ form_procesos.rep_pro }}
          </div>
          
        </div>
        <!-- other -->
        <div class="row mt-4">       
            <div class="col-6">
              
              <span id="label_doc_pro">{{ form_procesos.doc_pro.label }}</span>
              {{ form_procesos.doc_pro }}
            </div>
          <div class="col-6">
            <span id="label_usuarioid">{{ form_procesos.usuarioid.label }}</span> <br>
            {{ form_procesos.usuarioid }}
          </div>
        </div>
        <!-- finother -->
         <!-- other -->
      <div class="row mt-4">       
        <div class="col-6">
          
          <span id="label_tipoprocesoid">{{ form_procesos.tipoprocesoid.label }}</span> <br>
            {{ form_procesos.tipoprocesoid }}
        </div>
      <div class="col-6">
        
        <span id="label_programaid">{{ form_procesos.unidadesid.label }}</span> <br>
          {{ form_procesos.unidadesid }}
      </div>
    </div>
    <!-- finother -->
    <!-- other -->
    <div class="row mt-4">       
      <div class="col">
  
        <span id="label_responsableid">{{ form_procesos.responsableid.label }}</span> <br>
        {{ form_procesos.responsableid }}
      </div>
    <div class="col">
      <span id="label_plataformaid">{{ form_procesos.plataformaid.label }}</span> <br>
      {{ form_procesos.plataformaid }}
    </div>
  </div>
  <!-- finother -->
        <!-- other -->
        <div class="row mt-4">       
          <div class="col-6">
            <span id="label_pre_pro">{{ form_procesos.pre_pro.label }}</span><br>
            {{ form_procesos.pre_pro }}
          </div>
        <div class="col-6">
          <span id="label_res_pro">{{ form_procesos.res_pro.label }}</span><br>
        {{ form_procesos.res_pro }}
        </div>
      </div>
      <!-- finother -->
      <!-- other -->
      <div class="row mt-4">       
        <div class="col-md-auto">
          <span id="label_tie_pro">{{ form_procesos.tie_pro.label }}</span> <br>
        {{ form_procesos.tie_pro }}
        <span id="label_tie_sel">{{ form_procesos.tie_sel.label }}</span>
        {{ form_procesos.tie_sel }}
        </div>

    </div>
    <!-- finother -->
       
      </div>

      <div>
        <span id="label_aut_pro">{{ form_procesos.aut_pro.label }}</span>
        {{ form_procesos.aut_pro }}
      </div>

      <br />
      <div class="container text-center">
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <button type="submit" id="tamaño">Guardar</button>
          </div>
        </div>
      </div>
    </form>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_unidadesid").change(function () {
        const url = $("#personForm").attr("data-responsable-url");
        const countryId = $(this).val(); 

        $.ajax({
            url: url,
            data: {
                'unidades_id': countryId
            },
            success: function (data) {
                $("#id_responsableid").html(data);
            }
        });

    });
</script>

  </body>
</html>